project:
  type: book

book:
  title: "Book of Workshops"
  #downloads: [pdf, epub]
  repo-url: https://github.com/ysph-dsde/Book-of-Workshops
  repo-actions: edit
  search: true
  reader-mode: true
  sidebar:
    style: "docked"
  date: 04/13/2025
  date-format: long
  chapters:
    - index.qmd
    - part: Git-and-GitHub/index.qmd
      chapters: 
        - Git-and-GitHub/git-github-setup.qmd
        - Git-and-GitHub/git-github-worked-through-example.qmd
        - Git-and-GitHub/git-github_references.qmd
    - part: Data-Visualization-with-ggplot2/index.qmd
      chapters: 
        - Data-Visualization-with-ggplot2/visualization-worked-through-example.qmd
  page-footer:
    background: light 
    left: "This site was built on a ysph-dsde.github.io page. It was rendered using Quarto (v 1.6.3) and theme [bookup-html](https://github.com/juba/bookup-html/tree/main)." 
    right: 
      - icon: globe
        href: https://ysph.yale.edu/public-health-research-and-practice/research-centers-and-initiatives/public-health-data-science-and-data-equity/
      - icon: github
        href: https://github.com/ysph-dsde
      - icon: linkedin 
        href: https://www.linkedin.com/showcase/public-health-data-science-and-data-equity-at-yale/
      - icon: envelope 
        href: mailto:admin.dsdeysph@yale.edu
      - text: "(203) 737-8644"

format:
  bookup-html:
    html-math-method: katex
    toc: true
    toc-depth: 3
    callout-appearance: default
  pdf:
    documentclass: scrreprt

editor: source

